backend/controllers/PnsmainController.php
<?php

namespace backend\controllers;

use Yii;
use mPDF;
use backend\models\Pnsmain;
use backend\models\Pnsgaji15;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\SqlDataProvider;
use yii\filters\AccessControl;
use yii\web\UploadedFile;
/**
 * PnsmainController implements the CRUD actions for Pnsmain model.
 */
class PnsmainController extends Controller
{
    public $skpd='';
    
    public function behaviors()
    {
    
        return [
                'access'=>[
            'class'=> AccessControl::className(),
            'rules'=>[
                [
                    'actions'=>['pnsmain','error','create','update'],
                    'allow'=>true,
                ],
                [
                    'actions'=>['logout','index','view','topdf'],
                    'allow'=>true,
                    'roles'=>['@'],
                ],
            ],
        ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pnsmain models.
     * @return mixed
     */
    public function PnsQuery(){
     
    if (isset($_GET['kdskpd'])){
         $kdskpd=trim($_GET['kdskpd']);
         if (substr($kdskpd,0,1)=='9'){
             $lcFilter = " ";
          
         }else{
             $lcFilter = "AND LEFT(B.kdskpd,1) != '9' ";
        
        
             if (strlen($kdskpd)>7){
                 $lcFilter = $lcFilter . "AND B.kdskpd = '". $kdskpd ."'";
             }else{
           $lcFilter = $lcFilter . "AND left(B.kdskpd,7) = '". $kdskpd ."'";
                 
             }
              if (isset($_GET['nip'])){
               
               $nip="AND CONCAT_WS('',A.nama,B.nip) LIKE '%".trim($_GET['nip'])."%'";
             $lcFilter = $lcFilter . $nip;
            
         }    
      }
        }else{
             $lcFilter=" ";
         
        }
        
      
         $key="nip";
    $sql1="SELECT COUNT(*) FROM pnsmain A " 
                 . " INNER JOIN pnsgaji15 B ON (A.nip = B.nip) "
                  . " inner join ref_skpd C on (B.kdskpd=C.kdskpd)  WHERE C.tahun='2015' and length(C.kdskpd)>7 and B.bulan = '04' $lcFilter "
                  . " ORDER BY B.kdgol DESC, B.rp_bersih DESC, A.nama ASC";
    
$sql="SELECT A.nip, A.nama, B.kdgol, B.status, A.jnskel, B.user, A.nipold, B.kdskpd,C.uraian,C.tahun FROM pnsmain A "
                  . " INNER JOIN pnsgaji15 B ON (A.nip = B.nip) "
                  . " inner join ref_skpd C on (B.kdskpd=C.kdskpd)  WHERE C.tahun='2015' and length(C.kdskpd)>7 and B.bulan = '04' $lcFilter "
                  . " ORDER BY B.kdgol DESC, B.rp_bersih DESC, A.nama ASC";
$count=  \Yii::$app->db->createCommand($sql1)->queryScalar();

$dataProvider=new SqlDataProvider(['sql'=>$sql, 
  //  'keyField' => $key,
    'totalCount'=>$count,
    'sort'=>[
      
        'attributes'=>[
             'uraian','nip','nama','kelahiran','tgllahir','kdgol','jnskel',
            'bulan', 'rp_pokok','rp_istri','rp_anak','rp_struk',
            'rp_fung','rp_umum','rp_tambah','rp_beras','rp_pajak',
            'rp_kotor','rp_iwp','pot_tprm','pot_sewa','pot_lebih',
            'pot_lain2','rp_totpot','rp_bersih'
        ],
   ],
    'pagination'=>[
        'pageSize'=>100,
    ],
]);
return $dataProvider;
    }
    public function actionIndex()
    {
     
        
        /* $dataProvider = new ActiveDataProvider([
            'query' => Pnsmain::find(),
        ]);
        * 
        */
        $dataProvider=  $this->PnsQuery();
        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }
/**
 *  View Single Report
 * @param string $nip
 * 
 */
    
    public function actionTopdf($nip){
          $sql="select A.nip,B.nama,A.kdgol,C.uraian from pnsmain B
inner join pnsgaji15 A on B.nip=A.nip
inner join ref_pangkat C on A.kdgol=C.kdgol
where A.bulan='05' and left(A.kdskpd,1)!='9' and A.nip=:nip";
    $conn=  Yii::$app->db;
    $cmd=$conn->createCommand($sql);
    $cmd->bindParam(':nip', $nip);
    $data=$cmd->queryOne();
    
        $mpdf = new mPDF();
        $mpdf->writeHTML(
                $this->renderPartial('print',array(
			'data' => $data,
                        
		),TRUE)
                );
        $mpdf->Output();
        exit();        
    }

    /**
     * Displays a single Pnsmain model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id,$kdskpd)
    {
        
        $sql="SELECT A.nip, A.nama,A.agama,A.kelahiran,A.tgllahir, A.jnskel, A.nipold, A.alamat,"
                  . " B.kdgol, B.status,B.user, B.kdskpd,C.uraian,C.tahun FROM pnsmain A "
                  . " INNER JOIN pnsgaji15 B ON (A.nip = B.nip) "
                  . " inner join ref_skpd C on (B.kdskpd=C.kdskpd)  WHERE C.tahun='2015' and length(C.kdskpd)>7 and B.bulan = '04' "
                  . " And B.nip =:id And B.kdskpd=:kdskpd "
                  . " ORDER BY B.kdgol DESC, B.rp_bersih DESC, A.nama ASC";
        $conn=\Yii::$app->db;
        $cmd=$conn->createCommand($sql);
        $cmd->bindParam(":id", $id);
        $cmd->bindParam(":kdskpd", $kdskpd);
        $model=$cmd->queryOne();
        return $this->render('view', [
            'model' => $model,//$this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pnsmain model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pnsmain();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 
                'id' => $model->nip,
                ]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pnsmain model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($nip,$kdskpd)
    {
//        $modelx = New Pnsmain();
 
        $model = $this->findModel($nip);
       
        if ($model->load(Yii::$app->request->post())) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
    //          $model->imageFile->saveAs('uploads/'.$nameimg.'.'.$model->imageFile->extension);
      if ($model->upload()){   
            $model->save();
             Yii::$app->session->setFlash('success', 'Update Sukses');
            return $this->redirect(['view', 
                'id' => $model->nip,
                  'kdskpd'=>  $kdskpd
]);
        } }
            return $this->render('update', [
                'model' => $model,
            ]);
        
    }

    /**
     * Deletes an existing Pnsmain model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($nip)
    {
        $this->findModel($nip)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pnsmain model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Pnsmain the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($nip)
    {
        if (($model = Pnsmain::findOne($nip)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/RefskpdController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Refskpd;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;

/**
 * RefskpdController implements the CRUD actions for Refskpd model.
 */
class RefskpdController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Refskpd models.
     * @return mixed
     */
    public function actionIndex()
    {
        $kdskpd=Yii::$app->request->post('kdskpd');
       $sql="select kdskpd,uraian,tahun from ref_skpd where tahun=2014 "
               . " and CONCAT_WS('',uraian,kdskpd) LIKE '%".$kdskpd."%'"; 
        $dataProvider = new ActiveDataProvider([
            'query' =>  Refskpd::findBySql($sql),
            'pagination'=>[
                'pageSize'=>10
            ]
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Refskpd model.
     * @param string $tahun
     * @param string $kdskpd
     * @return mixed
     */
    public function actionView($tahun, $kdskpd)
    {
        return $this->render('view', [
            'model' => $this->findModel($tahun, $kdskpd),
        ]);
    }

    /**
     * Creates a new Refskpd model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Refskpd();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'tahun' => $model->tahun, 'kdskpd' => $model->kdskpd]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Refskpd model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $tahun
     * @param string $kdskpd
     * @return mixed
     */
    public function actionUpdate($tahun, $kdskpd)
    {
        $model = $this->findModel($tahun, $kdskpd);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'tahun' => $model->tahun, 'kdskpd' => $model->kdskpd]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Refskpd model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $tahun
     * @param string $kdskpd
     * @return mixed
     */
    public function actionDelete($tahun, $kdskpd)
    {
        $this->findModel($tahun, $kdskpd)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Refskpd model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $tahun
     * @param string $kdskpd
     * @return Refskpd the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($tahun, $kdskpd)
    {
        if (($model = Refskpd::findOne(['tahun' => $tahun, 'kdskpd' => $kdskpd])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<!--
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
    reserved.
</footer>
-->
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class='control-sidebar-menu'>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-waring pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href='javascript::;'>
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->

        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked/>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right"/>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

backend/views/layouts/footer.php
 <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.0
        </div>
        <strong>Copyright &copy; 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
      </footer>

backend/views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">
    <?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">

              
                <!-- User Account: style can be found in dropdown.less -->

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?= Yii::$app->user->identity->username; ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle"
                                 alt="User Image"/>

                            <p>
                                <?= Yii::$app->user->identity->username; ?> - Tukang Ketik
                                <small>Bagawi pas Ada Nang Digawi</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                         <!--   <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                         -->
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <?= Html::a(
                                    'Sign out',
                                    ['/site/logout'],
                                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            </div>
                        </li>
                    </ul>
                </li>

            
            </ul>
        </div>
    </nav>
</header>

backend/views/layouts/left.php
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $directoryAsset ?>/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= Yii::$app->user->identity->username; ?></p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form -->
      <!--  <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form> -->
        <!-- /.search form -->

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu'],
                'items' => [
                    ['label' => 'Menu Navigation', 'options' => ['class' => 'header']],
                    ['label' => 'Pegawai', 'icon' => 'fa fa-file-code-o', 'url' => ['/pnsmain/index']],
                  [
                        'label' => 'Data Maser',
                        'icon' => 'fa fa-share',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Ref Skpd', 'icon' => 'fa fa-file-code-o', 'url' => ['/refskpd/index'],],
                            ['label' => 'Tentang', 'icon' => 'fa fa-dashboard', 'url' => ['/site/about'],],
                            ['label' => 'Gii', 'icon' => 'fa fa-file-code-o', 'url' => ['/gii']],
                            /*[
                                'label' => 'Level One',
                                'icon' => 'fa fa-circle-o',
                                'url' => '#',
                                'items' => [
                                    ['label' => 'Level Two', 'icon' => 'fa fa-circle-o', 'url' => '#',],
                                    [
                                        'label' => 'Level Two',
                                        'icon' => 'fa fa-circle-o',
                                        'url' => '#',
                                        'items' => [
                                            ['label' => 'Level Three', 'icon' => 'fa fa-circle-o', 'url' => '#',],
                                            ['label' => 'Level Three', 'icon' => 'fa fa-circle-o', 'url' => '#',],
                                        ],
                                    ],
                                ],
                            ],
                            */
                        ],
                    ],
                    ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
                    
                ],
            ]
        ) ?>

    </section>

</aside>

backend/views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') { 
/**
 * Do not use this code in your template. Remove it. 
 * Instead, use the code  $this->layout = '//main-login'; in your controller.
 */
    echo $this->render(
        'main-login',
        ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>

backend/views/layouts/mainx.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
        ['label'=>'Pegawai','url'=>['/pnsmain/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = [
            'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
            'url' => ['/site/logout'],
            'linkOptions' => ['data-method' => 'post']
        ];
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>