backend/models/Pnsmain.php
<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;

/**
 * This is the model class for table "pnsmain".
 *
 * @property string $nip
 * @property string $nama
 * @property string $kelahiran
 * @property string $tgllahir
 * @property string $jnskel
 * @property string $agama
 * @property string $rekbank
 * @property string $npwp
 * @property string $sekolah
 * @property string $alamat
 * @property string $karpeg
 * @property string $nipold
 * @property string $btspens
 * @property string $stssertf
 * @property string $kdsertf
 * @property string $stsout
 * @property string $tglout
 * @property string $ketout
 * @property string $blnout
 * @property string $user
 * 
 */
class Pnsmain extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     *  @var UploadedFile
     */
    
   public $imageFile;
    public static function tableName()
    {
        return 'pnsmain';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nip', 'nipold','imageFile'], 'required'],
            [['tgllahir', 'btspens', 'tglout'], 'safe'],
            [['jnskel', 'alamat', 'stssertf', 'ketout'], 'string'],
            [['nip', 'nipold'], 'string', 'max' => 21],
            [['nama'], 'string', 'max' => 40],
            [['kelahiran', 'sekolah'], 'string', 'max' => 30],
            [['agama', 'stsout'], 'string', 'max' => 1],
            [['rekbank'], 'string', 'max' => 25],
              [['imageFile'], 'file', ],
            [['npwp', 'kdsertf', 'user'], 'string', 'max' => 20],
            [['karpeg'], 'string', 'max' => 7],
            [['blnout'], 'string', 'max' => 4],
        ];
    }

    public function upload()
    {
         $nameimg= Yii::$app->MyComponent->nip($this->nip);
        if ($this->validate()){
            $this->imageFile->saveAs('uploads/'.$nameimg.'.'.$this->imageFile->extension);
            return true;
        }else{
            return false;
        }
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'nip' => 'Nip',
            'nama' => 'Nama',
            'kelahiran' => 'Kelahiran',
            'tgllahir' => 'Tgllahir',
            'jnskel' => 'Jnskel',
            'agama' => 'Agama',
            'rekbank' => 'Rekbank',
            'npwp' => 'Npwp',
            'sekolah' => 'Sekolah',
            'alamat' => 'Alamat',
            'karpeg' => 'Karpeg',
            'nipold' => 'Nipold',
            'btspens' => 'Btspens',
            'stssertf' => 'Stssertf',
            'kdsertf' => 'Kdsertf',
            'stsout' => 'Stsout',
            'tglout' => 'Tglout',
            'ketout' => 'Ketout',
            'blnout' => 'Blnout',
            'user' => 'User',
            'kdgol'=>'Gol.',
            'uraian'=>'Nama SKPD',
            'imageFile'=> 'Upload Foto'
        ];
    }
    
    public static function Nip($nipx){
        $lnawal = substr($nipx, 0, 8);
        $lntengah = substr($nipx, 8, 6);
        $lntengahx = substr($nipx, 14, 1);
        $lnakhir = substr($nipx, -3, 3);
       $nipnew=$lnawal . ' ' . $lntengah . ' ' . $lntengahx . ' ' . $lnakhir;
        return $nipnew;
    }
       public static function getSkpd()
    {
        $droptions=  Refskpd::findBySql("Select kdskpd,uraian from ref_skpd where tahun='2015' and length(kdskpd)>7")->all();
        return ArrayHelper::map($droptions, 'kdskpd', 'uraian');
    }

}

backend/controllers/Pnsgaji15Controller.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Pnsgaji15;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\SqlDataProvider;
/**
 * Pnsgaji15Controller implements the CRUD actions for Pnsgaji15 model.
 */
class Pnsgaji15Controller extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pnsgaji15 models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Pnsgaji15::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Pnsgaji15 model.
     * @param string $bulan
     * @param string $nip
     * @return mixed
     */
    public function actionView($bulan, $nip)
    {
        return $this->render('view', [
            'model' => $this->findModel($bulan, $nip),
        ]);
    }
    /**
     * Menampilkan Query Gaji Berdasarkan Nip dan Skpd.
     * Jika benar, akan menampilkan ke view/gridview.
     * @return dataprovider
     */
    public function actionList($id,$kdskpd)
{
        $nip=  $this->Nip($id);
        $sql="select A.*,B.nama,C.uraian as nmgol from pnsgaji15 A"
            . " inner join pnsmain B on A.nip=B.nip "
            . " inner join ref_pangkat C on A.kdgol=C.kdgol "
            . " where A.nip='$nip' and A.kdskpd='$kdskpd' and A.bulan='04'";
        
        $conn= Yii::$app->db;
        $cmd=$conn->createCommand($sql);
        $users=$cmd->queryAll();
    \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
   // $users = \app\models\User::find()->all();
    return $users;
}

public function GajiQuery($id,$kdskpd)
 {
 $nip=$id;
    
    $sql1="select COUNT(*) from pnsgaji15 A"
            . " inner join pnsmain B on A.nip=B.nip "
            . " inner join ref_pangkat C on A.kdgol=C.kdgol "
            . " where A.nip='$nip' and A.kdskpd='$kdskpd' and A.bulan='04'";
    
$sql="select A.*,B.nama,C.uraian as nmgol from pnsgaji15 A"
            . " inner join pnsmain B on A.nip=B.nip "
            . " inner join ref_pangkat C on A.kdgol=C.kdgol "
            . " where A.nip='$nip' and A.kdskpd='$kdskpd' and A.bulan='04'";
$count=  \Yii::$app->db->createCommand($sql1)->queryScalar();

$dataProvider=new SqlDataProvider(['sql'=>$sql, 
  //  'keyField' => $key,
    'totalCount'=>$count,
    'sort'=>[
      
        'attributes'=>[
             'uraian','nip','nama','kelahiran','tgllahir','kdgol','jnskel',
            'bulan', 'rp_pokok','rp_istri','rp_anak','rp_struk',
            'rp_fung','rp_umum','rp_tambah','rp_beras','rp_pajak','rp_bulat',
            'rp_kotor','rp_iwp','pot_tprm','pot_sewa','pot_lebih',
            'pot_lain2','rp_totpot','rp_bersih'
        ],
   ],
    'pagination'=>[
        'pageSize'=>100,
    ],
]);
 
/*$conn=  Yii::app()->db;
$cmd=$conn->createCommand($sql);
$dataProvider=$cmd->queryAll();
 return $dataProvider;
 * 
 */
return $dataProvider;
 }
 
    public function actionGaji($id,$kdskpd) {
      $sql="SELECT A.nip, A.nama,A.agama,A.kelahiran,A.tgllahir, A.jnskel, A.nipold, A.alamat,"
                  . " B.kdgol, B.status,B.user, B.kdskpd,C.uraian,C.tahun FROM pnsmain A "
                  . " INNER JOIN pnsgaji15 B ON (A.nip = B.nip) "
                  . " inner join ref_skpd C on (B.kdskpd=C.kdskpd)  WHERE C.tahun='2015' and length(C.kdskpd)>7 and B.bulan = '04' "
                  . " And B.nip =:id And B.kdskpd=:kdskpd "
                  . " ORDER BY B.kdgol DESC, B.rp_bersih DESC, A.nama ASC";
        $conn=\Yii::$app->db;
        $cmd=$conn->createCommand($sql);
        $cmd->bindParam(":id", $id);
        $cmd->bindParam(":kdskpd", $kdskpd);
        $model=$cmd->queryone();
       $dataProvider=  $this->GajiQuery($id,$kdskpd);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model'=>$model
        ]);
    }
    /**
     * Creates a new Pnsgaji15 model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pnsgaji15();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'bulan' => $model->bulan, 'nip' => $model->nip]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pnsgaji15 model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $bulan
     * @param string $nip
     * @return mixed
     */
    public function actionUpdate($bulan, $nip)
    {
        $model = $this->findModel($bulan, $nip);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'bulan' => $model->bulan, 'nip' => $model->nip]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Pnsgaji15 model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $bulan
     * @param string $nip
     * @return mixed
     */
    public function actionDelete($bulan, $nip)
    {
        $this->findModel($bulan, $nip)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pnsgaji15 model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $bulan
     * @param string $nip
     * @return Pnsgaji15 the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($bulan, $nip)
    {
        if (($model = Pnsgaji15::findOne(['bulan' => $bulan, 'nip' => $nip])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/Pnsrapel1Controller.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Pnsrapel1;
use backend\models\Pnsrapel1Search;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\data\SqlDataProvider;
/**
 * Pnsrapel1Controller implements the CRUD actions for Pnsrapel1 model.
 */
class Pnsrapel1Controller extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pnsrapel1 models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new Pnsrapel1Search();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
   /**
     * Menampilkan Query Gaji Berdasarkan Nip dan Skpd.
     * Jika benar, akan menampilkan ke view/gridview.
     * @return dataprovider
     */
public function RapelQuery($id,$kdskpd)
 {
 $nip=$id;
    
    $sql1="select COUNT(*) from pnsgaji15 A"
            . " inner join pnsmain B on A.nip=B.nip "
            . " inner join ref_pangkat C on A.kdgol=C.kdgol "
            . " where A.nip='$nip' and A.kdskpd='$kdskpd' and A.bulan='04'";
    
$sql="select A.*,B.nama,C.uraian as nmgol from pnsgaji15 A"
            . " inner join pnsmain B on A.nip=B.nip "
            . " inner join ref_pangkat C on A.kdgol=C.kdgol "
            . " where A.nip='$nip' and A.kdskpd='$kdskpd' and A.bulan='04'";
$count=  \Yii::$app->db->createCommand($sql1)->queryScalar();

$dataProvider=new SqlDataProvider(['sql'=>$sql, 
  //  'keyField' => $key,
    'totalCount'=>$count,
    'sort'=>[
      
        'attributes'=>[
             'uraian','nip','nama','kelahiran','tgllahir','kdgol','jnskel',
            'bulan', 'rp_pokok','rp_istri','rp_anak','rp_struk',
            'rp_fung','rp_umum','rp_tambah','rp_beras','rp_pajak','rp_bulat',
            'rp_kotor','rp_iwp','pot_tprm','pot_sewa','pot_lebih',
            'pot_lain2','rp_totpot','rp_bersih'
        ],
   ],
    'pagination'=>[
        'pageSize'=>100,
    ],
]);
 
/*$conn=  Yii::app()->db;
$cmd=$conn->createCommand($sql);
$dataProvider=$cmd->queryAll();
 return $dataProvider;
 * 
 */
return $dataProvider;
 }
 
    public function actionRapel($id,$kdskpd) {
      $sql="SELECT A.nip, A.nama,A.agama,A.kelahiran,A.tgllahir, A.jnskel, A.nipold, A.alamat,"
                  . " B.kdgol, B.status,B.user, B.kdskpd,C.uraian,C.tahun FROM pnsmain A "
                  . " INNER JOIN pnsgaji15 B ON (A.nip = B.nip) "
                  . " inner join ref_skpd C on (B.kdskpd=C.kdskpd)  WHERE C.tahun='2015' and length(C.kdskpd)>7 and B.bulan = '04' "
                  . " And B.nip =:id And B.kdskpd=:kdskpd "
                  . " ORDER BY B.kdgol DESC, B.rp_bersih DESC, A.nama ASC";
        $conn=\Yii::$app->db;
        $cmd=$conn->createCommand($sql);
        $cmd->bindParam(":id", $id);
        $cmd->bindParam(":kdskpd", $kdskpd);
        $model=$cmd->queryone();
       $dataProvider=  $this->RapelQuery($id,$kdskpd);
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model'=>$model
        ]);
    }
    /**
     * Displays a single Pnsrapel1 model.
     * @param string $thnbln
     * @param string $nip
     * @param integer $urut
     * @return mixed
     */
    public function actionView($thnbln, $nip, $urut)
    {
        return $this->render('view', [
            'model' => $this->findModel($thnbln, $nip, $urut),
        ]);
    }

    /**
     * Creates a new Pnsrapel1 model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pnsrapel1();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'thnbln' => $model->thnbln, 'nip' => $model->nip, 'urut' => $model->urut]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Pnsrapel1 model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $thnbln
     * @param string $nip
     * @param integer $urut
     * @return mixed
     */
    public function actionUpdate($thnbln, $nip, $urut)
    {
        $model = $this->findModel($thnbln, $nip, $urut);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'thnbln' => $model->thnbln, 'nip' => $model->nip, 'urut' => $model->urut]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Pnsrapel1 model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $thnbln
     * @param string $nip
     * @param integer $urut
     * @return mixed
     */
    public function actionDelete($thnbln, $nip, $urut)
    {
        $this->findModel($thnbln, $nip, $urut)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Pnsrapel1 model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $thnbln
     * @param string $nip
     * @param integer $urut
     * @return Pnsrapel1 the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($thnbln, $nip, $urut)
    {
        if (($model = Pnsrapel1::findOne(['thnbln' => $thnbln, 'nip' => $nip, 'urut' => $urut])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/pnsmain/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Pnsmain */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pnsmain-form">

    <?php $form = ActiveForm::begin([
	    'options' => [ 'enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'nip')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nama')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'kelahiran')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'tgllahir')->textInput() ?>

    <?= $form->field($model, 'jnskel')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'agama')->textInput(['maxlength' => true]) ?>

     <?= $form->field($model, 'alamat')->textarea(['rows' => 6]) ?>
       <?= $form->field($model,'imageFile' )->fileInput() ?>
     
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/pnsmain/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\PnsmainSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pnsmain-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'nip') ?>

    <?= $form->field($model, 'nama') ?>

    <?= $form->field($model, 'kelahiran') ?>

    <?= $form->field($model, 'tgllahir') ?>

    <?= $form->field($model, 'jnskel') ?>

    <?php // echo $form->field($model, 'agama') ?>

    <?php // echo $form->field($model, 'rekbank') ?>

    <?php // echo $form->field($model, 'npwp') ?>

    <?php // echo $form->field($model, 'sekolah') ?>

    <?php // echo $form->field($model, 'alamat') ?>

    <?php // echo $form->field($model, 'karpeg') ?>

    <?php // echo $form->field($model, 'nipold') ?>

    <?php // echo $form->field($model, 'btspens') ?>

    <?php // echo $form->field($model, 'stssertf') ?>

    <?php // echo $form->field($model, 'kdsertf') ?>

    <?php // echo $form->field($model, 'stsout') ?>

    <?php // echo $form->field($model, 'tglout') ?>

    <?php // echo $form->field($model, 'ketout') ?>

    <?php // echo $form->field($model, 'blnout') ?>

    <?php // echo $form->field($model, 'user') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/pnsmain/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Pnsmain */

$this->title = 'Create Pnsmain';
$this->params['breadcrumbs'][] = ['label' => 'Pnsmains', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pnsmain-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/pnsmain/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\pajax;
use backend\models\Pnsmain;
use kartik\select2\Select2;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\bootstrap\Button;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Detail PNS';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pnsmain-index">

    <h1><?= "Pencarian" ?></h1>
    <?php
    $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
    ]);
    ?>
    <div class="row">
        <div class="col-md-12">
            <?=
            Select2::widget([
                'id' => 'kdskpd',
                'name' => 'kdskpd',
                'value' => '',
                'data' => Pnsmain::getSkpd(),
                'options' => ['multiple' => false, 'placeholder' => 'Pilih SKPD ...']
            ]);
            ?>
        </div>
    </div>
    <br>

    <div class="row">
        <div class="col-md-12">
            <input type="text" class="form-control" name="nip" id="nip"></input>
        </div>
    </div>    <br>
    <div class="row">
        <div class="col-sm-5">
            <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
      <?= Html::a('Reset', ['index'], ['class' => 'btn btn-info']) ?>
            </div>
        </div>
    </div>
        <?php ActiveForm::end(); ?>
        <?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'pjax'=>true,
            'export'=>false,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                ['attribute' => 'uraian', 'format' => 'text', 'label' => 'Nama SKPD','headerOptions'=>['width'=>'100']],
                ['attribute' => 'nip', 'format' => 'text', 'label' => 'Nip','headerOptions'=>['width'=>'175']],
                 'nama:text:Nama',
                ['attribute' => 'kdgol', 'format' => 'text', 'label' => 'Gol.','headerOptions'=>['width'=>'40']],
              
               
                ['class' => 'yii\grid\ActionColumn',
                    'template' => '{view} {gaji} {rapel}',
                    'buttons' => [
                        'view' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-th-list"> View</span>', $url, [
                                      ' class'=>"btn btn-default btn-flat",
                                'title' => Yii::t('yii', 'View'),
                                            'style'=>'width : 90px',
                            ]);
                        },
                                'gaji' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-bitcoin"> Gaji</span>', $url, [
                                 'class'=>"btn btn-danger btn-flat",
                                        'title' => Yii::t('yii', 'Gaji'),
                                 'style'=>'width : 90px;'
                            ]);
                        },
                                'rapel' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-rub"> Rapel</span>', $url, [
                                        'class'=>"btn btn-info btn-flat",
                                'title' => Yii::t('yii', 'Rapel'),
                                'style'=>'width : 90px'
                            ]);
                        },
                            ],
                            'urlCreator' => function ($action, $model, $key, $index) {
                        if ($action === 'view') {
                            $url = Url::to(['view', 'id' => $model["nip"], 'kdskpd' => $model["kdskpd"]]);
                            return $url;
                        }
                              if ($action === 'gaji') {
                            $url = Url::to(['pnsgaji15/gaji', 'id' => $model["nip"], 'kdskpd' => $model["kdskpd"]]);
                            return $url;
                        }
                               if ($action === 'rapel') {
                            $url = Url::to(['pnsrapel1/rapel', 'id' => $model["nip"], 'kdskpd' => $model["kdskpd"]]);
                            return $url;
                        }
                    }
                    
                        ]],
                ]);
                ?>

    </div>

backend/views/pnsmain/print.php
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta content="text/html; charset=ISO-8859-1"
 http-equiv="content-type">
  <title></title>
</head>
<body>
<table style="text-align: left; width: 100%; height: 168px;"
 border="1" cellpadding="2" cellspacing="2">
  <tbody>
    <tr>
      <td style="height: 164px;">DINAS PENDIDIKAN</td>
    </tr>
  </tbody>
</table>
<br>
<table style="text-align: left; width: 862px; height: 159px;"
 border="1" cellpadding="2" cellspacing="2">
  <tbody>
    <tr>
      <td style="width: 84px;">nip</td>
      <td style="width: 4px;">:</td>
      <td style="width: 172px;"><?= $data['nip']; ?></td>
      <td style="width: 566px;" colspan="1" rowspan="3"></td>
    </tr>
    <tr>
      <td style="width: 84px;">nama</td>
      <td style="width: 4px;">:</td>
      <td style="width: 172px;"><?= $data['nama'] ?></td>
    </tr>
    <tr>
      <td style="width: 84px;">pangkat</td>
      <td style="width: 4px;">:</td>
      <td style="width: 172px;"><?= $data['uraian'] ?></td>
    </tr>
  </tbody>
</table>
<br>
</body>
</html>

backend/views/pnsmain/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Pnsmain */

$this->title = 'Update Pnsmain: ' . ' ' . $model->nip;
$this->params['breadcrumbs'][] = ['label' => 'Pnsmains', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->nip, 'url' => ['view', 'id' => $model->nip]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pnsmain-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/pnsmain/view_1.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\models\Pnsmain */

$this->title = $model->nip;
$this->params['breadcrumbs'][] = ['label' => 'Pnsmains', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pnsmain-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->nip], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->nip], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'nip',
            'nama',
            'kelahiran',
            'tgllahir',
            'jnskel',
            'agama',
            'rekbank',
            'npwp',
            'sekolah',
            'alamat:ntext',
            'karpeg',
            'nipold',
            'btspens',
            'stssertf',
            'kdsertf',
            'stsout',
            'tglout',
            'ketout:ntext',
            'blnout',
            'user',
        ],
    ]) ?>

</div>